# Generated by Django 5.1.5 on 2025-10-25 12:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Earning',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('job_name', models.CharField(max_length=200)),
                ('invoice_number', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('image1', models.ImageField(upload_to='earnings_images/')),
                ('image2', models.ImageField(blank=True, null=True, upload_to='earnings_images/')),
                ('date', models.DateField()),
            ],
        ),
    ]
